# Global settings applied to the whole site.  
# 
# “publish” is the directory to publish (relative to root of your repo),
# “command” is your build command,
# “base” is directory to change to before starting build. if you set base:
#    that is where we will look for package.json/.nvmrc/etc not repo root!

[build]
  publish = "dist"
  command = "python main.py"

[template.environment]
  TWITTER_CONSUMER_KEY = "set your consummer key you got from https://apps.twitter.com/"
  TWITTER_CONSUMER_PWD = "set your consummer pwd you got from https://apps.twitter.com/"
  TWITTER_ACCESS_TOKEN = "set the access token"
  TWITTER_ACCESS_PWD = "set the access pwd"
  TWITTER_ID = "set the twitter ID (without @)"
  TEMPLATE = "layout.html"
  MAX_POSTS = "Maximum depth of posts list (recommanded 40)"
  


